### ISSUE TITLE
Ability to user patterns for enum and model locations

### ISSUE THREAD

**Issue by huubvdw** [lenderspender/laravel-enums#4]
See https://github.com/barryvdh/laravel-ide-helper/pull/921/files

**Comment by BertvanHoekelen** [comment]
You can already specify enum locations by changing the `laravel-enums.php` configuration. See https://github.com/lenderspender/laravel-enums/pull/1. Folders are searched recursively. 

Example:
```php
<?php

return [
    'enum_locations' => [
        '/app/Domain/',
        '/app/Enums/',
    ],
    'model_locations' => [
        '/app/Domain/',
        '/app/Models/',
    ],
];
```
